apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: string-string
  labels:
    service: string
spec:
  description: "string de string: 99% en ventana 1h"
  target: "99"
  window: 1h
  indicator:
    ratio:
      errors:
        metric: sli_errors_total{service="string", check="string"}
      total:
        metric: sli_checks_total{service="string", check="string"}
